version: '3.6'
services:
  telegraf:
    image: telegraf:1.18-alpine
    user: root
    entrypoint: "telegraf"
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    ports:
      - '${PROJECT_HOSTNAME}:${TELEGRAF_PORT}:${TELEGRAF_PORT}/udp'

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '${PROJECT_HOSTNAME}:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    ports:
      - '${PROJECT_HOSTNAME}:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  php:
    build:
      context: ./php-example
    env_file:
      - ./.env
    depends_on:
      - telegraf
    volumes:
      - ./php-example/example.php:/var/www/html/example.php

volumes:
  grafana_data: { }
  influxdb_data: { }
